flickit-platform/flickit-platform

frontend/src/components/common/QueryData.tsx, frontend/src/components/expert-groups/ExpertGroupContainer.tsx
unpublished profiles bug fixed
=> OTAT-415(new)

frontend/src/components/spaces/SpaceSettingContainer.tsx
=> OTAT-435:space setting bug fixed

frontend/src/components/profile/ProfileExpertViewContainer.tsx, frontend/src/config/translations/en.json, frontend/src/service/index.ts
=> OTAT-420:conflict problem solved

frontend/src/components/common/SupTitleBreadcrumb.tsx, frontend/src/config/translations/en.json
=> OTAT-439:breadcrumb bug fixed

frontend/src/components/subject-report/SubjectContainer.tsx
attribute breadcrumb bug fixed
=> OTAT-439:attribute breadcrumb bug fixed

frontend/src/components/assessment-report/AssessmentOverallStatus.tsx, frontend/src/components/common/charts/Gauge.tsx, frontend/src/config/styles.ts
=> OTAT-451:color bug fixed

frontend/src/components/common/fields/SelectField.tsx
create assessment color option bug fixed
=> OTAT-440:create assessment color option bug fixed

frontend/src/components/common/fields/AutocompleteAsyncField.tsx, frontend/src/components/profile/ProfileSettingFormDialog.tsx
edit profile tag options bug fixed
=> OTAR-447:edit profile tag options bug fixed

frontend/src/components/profile/ProfileExpertViewContainer.tsx, frontend/src/components/profile/ProfileSettingFormDialog.tsx, frontend/src/service/index.ts
update profile new services applied
=> OTAT-448:update profile

frontend/src/components/assessment-report/AssessmentReportContainer.tsx
profile report page responsive bug fixxed and conflict resolved
=> OTAT-465:profile report page responsive bug fixxed

frontend/src/components/common/charts/Gauge.tsx
=> OTAT-470:gauge bug fixed

frontend/src/components/assessments/AssessmentCard.tsx, frontend/src/components/expert-groups/ExpertGroupContainer.tsx, frontend/src/components/profile/ProfileSettingFormDialog.tsx
all console.logs has been removed
=> OTAT-491:all console.logs has been removed

frontend/src/components/assessments/AssessmentCard.tsx, frontend/src/components/common/charts/Gauge.tsx, frontend/src/components/compare/ComparePartItem.tsx, frontend/src/components/compare/CompareResult.tsx, frontend/src/components/compare/CompareResultAssessmentsSection.tsx, frontend/src/components/compare/CompareTable.tsx, frontend/src/config/translations/en.json, frontend/src/utils/hasMaturityLevel.tsx
=> OTAT-501:compare bug fixed

frontend/src/components/assessments/AssessmentCard.tsx, frontend/src/components/questionnaires/QuestionnaireContainer.tsx, frontend/src/components/subject-report/SubjectAttributeCard.tsx, frontend/src/components/subject-report/SubjectOverallInsight.tsx, frontend/src/types.ts, frontend/src/utils/hasMaturityLevel.tsx, frontend/src/utils/hasMaturityLevelStatus.tsx
=> OTAT-501:status bug fixed

frontend/src/components/spaces/SpaceSettingContainer.tsx
space setting tittle bug fixed
=> OTAT-510:bug fixed

frontend/src/components/spaces/SpaceMembers.tsx, frontend/src/components/spaces/SpaceSettingContainer.tsx
=> OTAT-499:isOwner tag bug fixed

frontend/src/components/assessments/AssessmentContainer.tsx
add space setting in assessment list page
=> OTAT-515:add space setting in assessment list page

frontend/src/components/assessment-report/AssessmentReportTitle.tsx, frontend/src/config/translations/en.json
ECHNICAL DUE DILIGENCE REPORT OF [name] changed to [name] INSIGHTS
=> OTAT-517:aseessment title insight

frontend/src/components/expert-groups/ExpertGroupContainer.tsx
when user is member of expert group but is_expert is false unpublished profiles shouldn't appear bug fixed
=> OTAT-502:unpublished profile error bug fixed

frontend/src/components/common/charts/Gauge.tsx
dynamic import vite error fixed
=> OTAT-498:dynamic import vite error fixed

frontend/src/components/assessments/AssessmentContainer.tsx
=> OTAT-515:change setting icon position

frontend/src/components/assessment-kit/AssessmentKitContainer.tsx, frontend/src/components/common/Navbar.tsx
=> OTAT-485:resolve conflicts

frontend/src/components/assessment-kit/AssessmentKitExpertViewContainer.tsx, frontend/src/components/assessment-kit/AssessmentKitSectionGeneralInfo.tsx
=> OTAT-493:resolve conflicts

frontend/src/components/spaces/SpaceMembers.tsx
now when you want to invite a member that is already a space member server return an error object with code and message
=> OTAT-482:space invites error handeling

frontend/src/components/assessment-kit/AssessmentKitContainer.tsx, frontend/src/config/translations/en.json
after resolve conflict some part of code was missing 
that part of code added
=> OTAT-485:bug fixed

frontend/src/components/assessment-kit/AssessmentKitExpertViewContainer.tsx, frontend/src/components/assessment-kit/AssessmentKitSectionGeneralInfo.tsx, frontend/src/config/translations/en.json
=> OTAT-420:add analyze assessment kit

frontend/src/components/expert-groups/ExpertGroupContainer.tsx
fetch data after unpublished assessment kit
=> OTAT-576:fetch data after unpublished assessment kit

frontend/src/components/assessment-kit/AssessmentKitExpertViewContainer.tsx, frontend/src/components/assessment-kit/AssessmentKitSectionGeneralInfo.tsx, frontend/src/components/common/fields/RichEditorField.tsx, frontend/src/config/translations/en.json, frontend/src/service/index.ts
new design for assessment kit detail page info and stats section
=> OTAT-592:assessment kit info detail page

frontend/src/components/assessment-kit/AssessmentKitExpertViewContainer.tsx, frontend/src/components/assessment-kit/AssessmentKitSectionGeneralInfo.tsx, frontend/src/config/translations/en.json
remove setting icon and change Maturity Levels to Maturity levels and fix tags field bug
=> OTAT-592: setting icon and fix tags field bug

frontend/src/components/assessment-kit/AssessmentKitSectionGeneralInfo.tsx
=> OTAT-592:field error

frontend/src/components/assessment-kit/AssessmentKitSectionGeneralInfo.tsx
=> OTAT-626:fix about tag bug

frontend/src/components/assessment-kit/AssessmentKitSectionGeneralInfo.tsx
=> OTAT-663:likes and timed used fixed

frontend/src/components/assessment-kit/AssessmentKitSectionGeneralInfo.tsx, frontend/src/components/common/InfoItem.tsx
=> OTAT-661:fix subject item info

frontend/src/components/assessments/AssessmentCEFromDialog.tsx, frontend/src/config/constants.ts, frontend/src/service/index.ts
replace create assessment service
=> OTAT-651:replace create assessment service

frontend/src/components/assessments/AssessmentCEFromDialog.tsx, frontend/src/components/questionnaires/QuestionnaireCard.tsx, frontend/src/components/questionnaires/QuestionnaireContainer.tsx, frontend/src/components/questionnaires/QuestionnaireList.tsx, frontend/src/service/index.ts, frontend/src/types.ts
fetch questionnaires list and change get colors service url
=> OTAT-673: fetch questionnaires list

frontend/src/components/assessment-kit/AssessmentKitCEFromDialog.tsx, frontend/src/components/assessments/AssessmentCEFromDialog.tsx, frontend/src/config/constants.ts
dialog component for create assessment and create assessment kit bug fixed
=> OTAT-680:dialog bug fix

frontend/src/components/common/QANumberIndicator.tsx, frontend/src/components/questionnaires/QuestionnaireContainer.tsx, frontend/src/components/questions/QuestionCard.tsx, frontend/src/components/questions/QuestionThumb.tsx, frontend/src/components/questions/QuestionsProgress.tsx, frontend/src/components/questions/QuestionsReview.tsx, frontend/src/config/translations/en.json, frontend/src/types.ts
add not applicable to submit question answer and some minor issues in view insights button and questionnaires list
=> OTAT-694:not applicable

frontend/index.html, frontend/src/components/assessment-kit/AssessmentKitExpertViewContainer.tsx, frontend/src/components/common/Navbar.tsx, frontend/src/components/questions/QuestionCard.tsx, frontend/src/components/questions/QuestionsReview.tsx, frontend/src/config/theme.ts, frontend/src/utils/languageDetector.tsx
support farsi questions in question submit answer page and in assessment kit details and some minor bug fixes in space list in navbar and pathinfo wrong service call in assessment kit details page
=> OTAT-722:support farsi questions

frontend/src/components/assessments/AssessmentContainer.tsx
Reverts flickit-platform/flickit-platform#761
=> Revert "OTAT-1688: fix route"
